name: Build DSpico Video

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20241104
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract TinyUSB
        run: |
          mkdir -p libs/temp_extract
          unzip -q libs/tinyusb.zip -d libs/temp_extract
          rm -rf libs/tinyusb
          mv libs/temp_extract/tinyusb libs/tinyusb
          rm -rf libs/temp_extract

      - name: Build Libraries (libtwl7 & libtwl9)
        run: |
          make -C libs/libtwl7
          make -C libs/libtwl9

      - name: Build NDS Firmware
        run: |
          make

      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: "*.nds"
          name: dspicovideo-firmware
